-- V16: Fix seed user passwords and church assignments
-- Both V4 and V5 had INVALID bcrypt hashes for "password123"
-- V5 used $2b$ prefix which Spring Security handles, but the hash itself was wrong
-- Also seed users have NULL church_id (V6 added column without default)

-- Add missing ROLE_PLATFORM_ADMIN role
INSERT INTO roles (name) VALUES ('ROLE_PLATFORM_ADMIN')
ON CONFLICT (name) DO NOTHING;

-- Correct bcrypt-12 hash of "password123" generated by Spring Security's BCryptPasswordEncoder(12)
UPDATE users SET
    password = '$2a$12$fLRSqtAwbLH2UJhZmlnL1etot0cR8hNI2hsYr1DqcIKtNveTMPZWi',
    church_id = COALESCE(church_id, 1)
WHERE email IN (
    'admin@gracechurch.org',
    'pastor@gracechurch.org',
    'treasurer@gracechurch.org',
    'secretary@gracechurch.org',
    'member@gracechurch.org'
);
